spring.application.name=RoomMateMatchingApp
logging.level.org.springframework.security=DEBUG
# PostgreSQL Config
spring.datasource.url=jdbc:postgresql://localhost:5432/roommate_db
spring.datasource.username=postgres
spring.datasource.password=Omarr.2002

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server
server.port=8080

